services:
  bot:
    build: .
    container_name: bot
    depends_on:
      - lavalink
    networks:
      - lavalink

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx2G
      - SERVER_PORT=${LAVA_PORT}
      - LAVALINK_SERVER_PASSWORD=${LAVA_PASSWORD}
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/
    networks:
      - lavalink
    expose:
      - 2333
    ports:
      - "${LAVA_PORT}:${LAVA_PORT}"
      -
networks:
  lavalink:
    name: lavalink