services:

  bot:
    build: .
    container_name: bot
    depends_on:
      - lavalink
    networks:
      - lavalink-net

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:latest
    container_name: lavalink
    restart: unless-stopped
    environment:
      - SERVER_PORT=${LAVA_PORT}
      - LAVALINK_SERVER_PASSWORD=${LAVA_PASSWORD}
      - YOUTUBE_REFRESH_TOKEN=${YOUTUBE_REFRESH_TOKEN}
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    networks:
      - lavalink-net
    expose:
      - 2333
    ports:
      - "2333:2333"

networks:
  lavalink-net:
    name: lavalink-net